# Default values for dotnet-webapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Web API
appName: "dotnet-webapi"
containerPort: 8080
appNamespace: "dotnet-app"
aspnet_env: "Development"

# Database
dbHost: postgresql-primary.database
dbName: tododb
dbUser: dbuser

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: 957478052151.dkr.ecr.eu-central-1.amazonaws.com/dotnet-webapi
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Image tag
  tag: "v1.0.0-4"

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: "nginx"

resources: {}